### ISSUE TITLE
Unhandled error for missing api key

### ISSUE THREAD

**Issue by jneidel** [investoreight/i8-terminal#78]
```text
Traceback (most recent call last):
  File "/home/jneidel/.local/bin/i8", line 8, in <module>
    sys.exit(main())
  File "/home/jneidel/.local/lib/python3.10/site-packages/i8_terminal/main.py", line 161, in main
    cli(obj={})
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 1655, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/jneidel/.local/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/jneidel/.local/lib/python3.10/site-packages/i8_terminal/common/stock_info.py", line 53, in validate_ticker
    if value and value.replace(" ", "").upper() not in set(get_stocks_df()["ticker"]):
  File "/home/jneidel/.local/lib/python3.10/site-packages/i8_terminal/common/stock_info.py", line 36, in get_stocks_df
    results = investor8_sdk.StockInfoApi().get_all_active_companies()
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/api/stock_info_api.py", line 53, in get_all_active_companies
    (data) = self.get_all_active_companies_with_http_info(**kwargs)  # noqa: E501
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/api/stock_info_api.py", line 108, in get_all_active_companies_with_http_info
    return self.api_client.call_api(
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/api_client.py", line 148, in __call_api
    response_data = self.request(
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/api_client.py", line 338, in request
    return self.rest_client.GET(url,
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/rest.py", line 228, in GET
    return self.request("GET", url,
  File "/home/jneidel/.local/lib/python3.10/site-packages/investor8_sdk/rest.py", line 222, in request
    raise ApiException(http_resp=r)
investor8_sdk.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.14.0 (Ubuntu)', 'Date': 'Sat, 25 Feb 2023 13:34:50 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Expires': '-1'})
HTTP response body: b'Paramter `apiKey` is not provided or not valid!'
```

To reproduce: `i8 company details -k CNC` on a fresh install (no `i8 user login`).

**Comment by investoreight** [comment]
@jneidel Thanks for reporting this. The issue is fixed. Please update the app: `pip install --upgrade i8-terminal`
